apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: paved-road-app
    newName: paved-road-app
    newTag: local
patches:
  - path: pull-policy.yaml
